# Generated by Django 4.1.1 on 2022-12-04 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raceclub_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='raceclub',
            name='car_drive_unit',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='raceclub',
            name='car_overclocking',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='raceclub',
            name='car_rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='raceclub',
            name='car_transmission',
            field=models.CharField(default='', max_length=40),
        ),
    ]
