# Generated by Django 4.1.1 on 2022-12-04 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raceclub_app', '0002_raceclub_car_drive_unit_raceclub_car_overclocking_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='raceclub',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
