# Generated by Django 4.1.1 on 2022-12-07 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raceclub_app', '0003_raceclub_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raceclub',
            name='car_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
