# Generated by Django 4.1.1 on 2022-12-09 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raceclub_app', '0007_rename_users_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Characteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_body', models.CharField(max_length=100)),
                ('car_number_of_doors', models.IntegerField()),
                ('rudder_position', models.CharField(max_length=100)),
                ('car_release', models.DateField()),
                ('producing_country', models.CharField(max_length=100)),
                ('horsepower', models.CharField(max_length=100)),
            ],
        ),
    ]
