# Generated by Django 4.1.1 on 2022-12-09 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('raceclub_app', '0008_characteristic'),
    ]

    operations = [
        migrations.AddField(
            model_name='raceclub',
            name='characteristic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='raceclub_app.characteristic'),
        ),
    ]
