# Generated by Django 4.1.1 on 2022-12-09 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raceclub_app', '0010_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='nickname',
            field=models.CharField(max_length=60),
        ),
    ]
