# Generated by Django 4.1.1 on 2022-12-09 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raceclub_app', '0011_alter_feedback_name_alter_feedback_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='csrfmiddlewaretoken',
            field=models.CharField(default='', max_length=200),
        ),
    ]
