# Generated by Django 4.1.1 on 2022-12-09 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raceclub_app', '0012_feedback_csrfmiddlewaretoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='csrfmiddlewaretoken',
        ),
    ]
