# Generated by Django 4.1.1 on 2022-12-10 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raceclub_app', '0013_remove_feedback_csrfmiddlewaretoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='rating',
            field=models.IntegerField(),
        ),
    ]
